### PR TITLE
Update Assignment1.ipynb

### PR DESCRIPTION
**Pull request by lishengh**
Created file change

### CODE REVIEW

**Comment by hannorein** [comment]
A pull request for submitting assignments would be awesome in general, but for this course please submit the assignment via portal. Thanks!

**Comment by lishengh** [comment]
But for me I can not save file on my laptop in ipynb file.

**Comment by hannorein** [comment]
You have to find a way to do that. We talked about it in class. For example, you can download the entire repository as a zip file and extract the ipynb from there.

**Comment by lishengh** [comment]
How to download the ZIP file please?

**Comment by hannorein** [comment]
This is something you could easily google! 

screen shot 2017-09-19 at 11 58 27 pm

**Comment by lishengh** [comment]
I have already submit a wrong assignment, could I make change to it?

**Comment by hannorein** [comment]
Try resubmitting it now.

**Comment by lishengh** [comment]
How to  resubmit it please?

**Comment by hannorein** [comment]
On portal. Try resubmitting it now. If you continue to have trouble, please get in touch with one of the TAs.

**Comment by lishengh** [comment]
My questions have all been solved. Thanks professor!

**Pull request closed without merging**
